/**
 * IRoom Interface
 * 
 * Defines the shape of a Room object used throughout the application.
 * This contract ensures consistency between the backend API response, 
 * the Redux state, and the UI components.
 */
export interface IRoom {
  /** The unique identifier, typically generated by MongoDB or a similar NoSQL database */
  _id: string;

  /** The cost per night or booking period (ensure currency logic is handled at the UI level) */
  price: number;

  /** Flag to determine the availability status; used to toggle UI buttons and styling */
  isBooked: boolean;
}